# Generated by Django 2.2.10 on 2020-12-07 23:46

from django.db import migrations, models
import django.db.models.deletion
import json_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuthModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('questionData', json_field.fields.JSONField(default='null', help_text='Enter a valid JSON object')),
                ('questionType', models.IntegerField(choices=[(0, 'textbox'), (1, 'radio'), (2, 'checkbox')])),
                ('pollObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollData', to='poll.PollModel')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerData', json_field.fields.JSONField(default='null', help_text='Enter a valid JSON object', null=True)),
                ('dataStart', models.CharField(default='', max_length=20)),
                ('dataEnd', models.CharField(default='', max_length=20)),
                ('pollObjAnswer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollDataAnswer', to='poll.QuestionModel')),
                ('userObjAnswer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userData', to='poll.UserAuthModel')),
            ],
        ),
    ]
