# Generated by Django 2.2.10 on 2020-12-07 23:53

from django.db import migrations
import json_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20201208_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='answerData',
            field=json_field.fields.JSONField(default='0', help_text='Enter a valid JSON object', null=True),
        ),
    ]
